name : python application test with github actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install basic need
      run: |
        make install 
    - name: format code
      run: |
        make format
    - name: lint with pylint
      run: |
        make lint
    - name: test with source code
      run: |
        make test

      

